### PR TITLE
deploy λ function if local code ≠ s3 code

### PR DESCRIPTION
**Pull request by abargnesi**
Motivation

Assuming the S3 location is the canonical source for your λ code
it is right to deploy a function only when the code differs.

Previously the decision to update was base on either of three
things:
- function does not exist on AWS Lambda
- function JSON configuration has changed (local ≠ lambda)
- forced update using the <forceUpdate> setting

Changes

λ functions are deployed when the code package's MD5 hash
differs with the S3 object.

For example, say your code.zip file's hash is XXXY and S3's
object s3://yourpackages/code.zip has a hash of XXXZ. Your lambda
functions will be deployed in this case.

If the hashes match then no code changes were made, hence no
deployment is necessary. One could still <forceUpdate> if they
wanted to.

Code Changes

- Introduced outcome enum to determine if local function code
  differs with S3.
- Cleaned up create/update process to not rely on exception
  handing.
- Consistent use of String.format.

Problems

- MD5 hashes have the potential for collisions but it's probably
  unlikely. S3 only computes MD5 checksums for objects anyway. In
  the future we could compute SHA256 checksums and store on the
  objects though.

### CODE REVIEW

**Comment by abargnesi** [comment]
@SeanRoy Here is what I'm thinking. Wanted to see what you thought.

Haven't added tests yet. When I ran `mvn test` with AWS credentials set I see the following test failure:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.seanroy.plugins.LambdaTest
[ERROR] Error during processing
java.io.FileNotFoundException: src/test/resources/test-projects/basic-test/lambda-test-0.0.1-SNAPSHOT.jar (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.github.seanroy.plugins.DeployLambdaMojo.compareCodeWithS3(DeployLambdaMojo.java:549)
	at com.github.seanroy.plugins.DeployLambdaMojo.uploadJarToS3(DeployLambdaMojo.java:537)
	at com.github.seanroy.plugins.DeployLambdaMojo.execute(DeployLambdaMojo.java:99)
	at com.github.seanroy.plugins.LambdaTest.testBasic(LambdaTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.887 sec <<< FAILURE!
testBasic(com.github.seanroy.plugins.LambdaTest)  Time elapsed: 1.731 sec  <<< ERROR!
org.apache.maven.plugin.MojoExecutionException: src/test/resources/test-projects/basic-test/lambda-test-0.0.1-SNAPSHOT.jar (No such file or directory)
	at com.github.seanroy.plugins.DeployLambdaMojo.execute(DeployLambdaMojo.java:119)
	at com.github.seanroy.plugins.LambdaTest.testBasic(LambdaTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running com.github.seanroy.plugins.JsonUtilTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec

Results :

Tests in error: 
  testBasic(com.github.seanroy.plugins.LambdaTest): src/test/resources/test-projects/basic-test/lambda-test-0.0.1-SNAPSHOT.jar (No such file or directory)

Tests run: 4, Failures: 0, Errors: 1, Skipped: 0
```

It seems like the local function code JAR is missing on the branch.

**Comment by abargnesi** [comment]
This will certainly conflict #94. How do you want to proceed?

**Comment by abargnesi** [comment]
Any thoughts?

**Comment by SeanRoy** [comment]
Hi Tony, I'm sorry, I'm trying to do too many things at once.  I
accidentally merged your PR thinking I was merging a different one, so I
reverted it and your PR is now gone.  Could you please recreate it?

I'm going to merge Joe's PR, so unless you merged with his code, there may
be some conflicts to resolve.  Also I added the test jar to the resources
directory in the branch.



sean@nrby.com <brittany.campbell@ping4.com>  | nrby.com
Twitter <https://twitter.com/nrbynow>  |  Facebook
<https://www.facebook.com/nrbynow>  |  Instagram
<https://instagram.com/nrbynow/>  |  LinkedIn
<http://linkedin.com/company/nrby>
<http://linkedin.com/company/nrby>

This message is intended only for the use of the individual or entity named
above and may contain information which is privileged, confidential, and
not intended for disclosure. If you are not the intended recipient, you are
hereby notified that any disclosure, copying, distribution, dissemination
or use of this message is strictly prohibited. If you have received this
message in error, please accept our apology. We would very much appreciate
your notifying the sender immediately by return email. Thank you.

**Comment by abargnesi** [comment]
@SeanRoy no worries. I'll take a look at merging again and will open a PR when ready (likely tonight).

**Pull request merged**
